package net.ivango.config;

/**
 * Created by Ivan Golubev <igolubev@ea.com> on 4/4/16.
 */
public enum Properties {
    COFFEE_SELECT_PARALLELISM,
    PAYMENT_PARALLELISM,
    PICK_COFFEE_PARALLELISM,

    COFFEE_SELECTION_TIMEOUT,

    CASH_PAYMENT_TIMEOUT,
    CREDIT_PAYMENT_TIMEOUT,

    FIND_CUP_TIMEOUT,
    PUT_UNDER_THE_OUTLET_TIMEOUT,
    TAKE_CUP_AND_LEAVE_TIMEOUT,

    POUR_ESPRESSO_TIMEOUT,
    POUR_LATTE_TIMEOUT,
    POUR_MACCIATTO_TIMEOUT,
    POUR_CAPPUCHINO_TIMEOUT
}
